version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: readlist
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
  web:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DATABASE_URL: mysql+pymysql://myuser:mypass@db/readlist
    depends_on:
      - db
    command: >
      sh -c "sleep 10 && flask run --host=0.0.0.0"


volumes:
  db_data:
